apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: gitops-platform
  namespace: argocd
spec:
  description: GitOps delivery platform
  sourceRepos:
    - "https://github.com/vaishalisaini-tech/gitops-platform.git"
  destinations:
    - namespace: "demo-*"
      server: https://kubernetes.default.svc
  clusterResourceWhitelist:
    - group: "*"
      kind: "*"
